### PR TITLE
Added Watchlist File feature

### PR DESCRIPTION
**Pull request by ra4king**
When player joins and is not in the List<string> list, a new thread is spawned that reads the contents of the defined watchlist file and looks for the player's name, triggering an email.

### CODE REVIEW

**Comment by ra4king** [comment]
This has not yet been tested. I will need at least 1 more person to test this.

**Comment by theBrianCui** [comment]
What's the reason for starting a new thread to read the file? (Not saying it's wrong - I'm just curious and am still learning this stuff)

**Comment by ra4king** [comment]
It's a bad idea to do any kind of IO on a thread in a method that is supposed to return quickly. The PRoCon thread is shared by all plugins, reading an entire file every single time a player joins will only slow things down.

**Comment by theBrianCui** [comment]
Considering how often OnPlayerJoin is fired, we'd have significantly better performance if we cached the file in memory first instead of scanning it every single time. PRoCon runs the configuration commands when plugins are initialized, so we can save the text in a string[] as soon as the file path is configured.

**Comment by ra4king** [comment]
I was thinking of implementing a caching feature but that felt overkill considering that it's not that big of a file. Saving the file is a bad idea as that means it can't be edited when the plugin is running. The caching feature I had in mind would simply reload the file every few OnPlayerJoin instead of every single time but, again, that felt like overkill unless we experience performance problems.

**Comment by theBrianCui** [comment]
Ah, you have a good point - it wouldn't get updated until the layer is restarted. I still think we should have some sort of cache though; I'm weary about how PRoCon handles multi threading in quick succession (say, during an event, where twenty+ players join at once, or if there's a long queue and the round just finished).

I've manually tested your code and merged it, and have implemented a caching feature that refreshes the file when the cache is over three minutes old. That way we can have smooth performance over spikes of activity.

https://github.com/analytalica/WatchDog/tree/ra4king-master

I'll merge it into master and pass it on to Ops in a few days unless you see anything that needs to be changed. The version in the link above is currently live on the Dev server; the config file is set to Configs/WatchDog.txt which you can try out.

**Comment by ra4king** [comment]
I looked through the changes and the code in general and I approve of what you've done. I didn't know there could be a time where 20+ players join at once!! That definitely would be _really_ bad for the system to spawn a new thread per player. I thought it was max a few at once and that wasn't too bad but your caching looks good. I'd make the time configurable though!

EDIT: Accidentally hit close... heh

**Comment by theBrianCui** [comment]
Hey Roi, are you still making changes to this?

**Comment by ra4king** [comment]
Is there anything you would like me to do?

**Comment by theBrianCui** [comment]
Oh. Oh. Oops! I misread your previous comment. I thought you weren't done :)

I'll manually merge everything and send it off.

**Pull request closed without merging**
